"""Builds gui/frontend/src/css/pg.css from the design system (docs/internal/Design).

The design system ships tokens.css and components/bundle.css with the textures
inlined as data URIs (~150 KB). The app keeps them as files instead: they are
cached, decoded once, and the stylesheet stays ~65 KB of rules. Run after the
design system changes:

    python tools/design-css/build.py

Needs Pillow only to (re)write the grain WebP files.
"""
import base64
import io
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from units import px_to_rem  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[2]
DESIGN = ROOT / "docs" / "internal" / "Design"
OUT = ROOT / "gui" / "frontend" / "src"

tokens = (DESIGN / "tokens.css").read_text(encoding="utf-8")
bundle = (DESIGN / "components" / "bundle.css").read_text(encoding="utf-8")

# Fonts live in src/fonts, the stylesheet in src/css.
tokens = tokens.replace('url("fonts/', 'url("../fonts/')

# Texture variables: grain as WebP files, rings from the procedural generator
# (js/rings.js sets --tex-rings-gen-*) with the design tile as the fallback.
grains = re.findall(r'--tex-grain:url\("data:image/png;base64,([^"]+)"\)', bundle)
assert len(grains) == 2, "expected light and dark grain"
try:
    from PIL import Image

    for name, b64 in zip(("light", "dark"), grains):
        img = Image.open(io.BytesIO(base64.b64decode(b64)))
        img.save(OUT / "img" / f"grain-{name}.webp", "WEBP", lossless=True, method=6)
except ImportError:
    print("Pillow missing: grain WebP files not rewritten")

bundle = re.sub(
    r':root,\[data-theme="light"\]\{--tex-rings:url\("data:[^"]+"\);--tex-grain:url\("data:[^"]+"\)\}',
    ':root,[data-theme="light"]{--tex-rings:var(--tex-rings-gen-light,url(../img/rings-light.svg));--tex-grain:url(../img/grain-light.webp)}',
    bundle,
)
bundle = re.sub(
    r'\[data-theme="dark"\]\{--tex-rings:url\("data:[^"]+"\);--tex-grain:url\("data:[^"]+"\)\}',
    '[data-theme="dark"]{--tex-rings:var(--tex-rings-gen-dark,url(../img/rings-dark.svg));--tex-grain:url(../img/grain-dark.webp)}',
    bundle,
)
assert "data:image" not in bundle, "an inlined image is left"

# The design ships px; the app's standard is rem (tools/design-css/units.py).
header = "/* GENERATED by tools/design-css/build.py from docs/internal/Design (px converted to rem). Do not edit: app styles go in app.css. */\n"
(OUT / "css" / "pg.css").write_text(header + px_to_rem(tokens + "\n" + bundle), encoding="utf-8", newline="\n")
print("pg.css", (OUT / "css" / "pg.css").stat().st_size, "bytes")

# The user guide for the Docs screen: docs/guide.{ru,en}.md and the images it
# shows, copied next to the UI (the gui module cannot embed files above it).
import shutil
DOCS = ROOT / "docs"
(OUT / "docs" / "imgs").mkdir(parents=True, exist_ok=True)
for old in (OUT / "docs" / "imgs").glob("*"):
    old.unlink()
for lang in ("ru", "en"):
    text = (DOCS / f"guide.{lang}.md").read_text(encoding="utf-8")
    for img in set(re.findall(r"!\[[^\]]*\]\((imgs/[^)]+)\)", text)):
        if not (DOCS / img).exists():  # the guide may name an image not drawn yet
            print("missing guide image:", img)
            continue
        webp = str(pathlib.PurePosixPath(img).with_suffix(".webp"))
        try:  # WebP: a quarter of the PNG, it ships inside the exe
            from PIL import Image
            Image.open(DOCS / img).save(OUT / "docs" / webp, "WEBP", quality=82, method=6)
            text = text.replace(f"({img})", f"({webp})")
        except ImportError:
            shutil.copyfile(DOCS / img, OUT / "docs" / img)
    (OUT / "docs" / f"guide.{lang}.md").write_text(text, encoding="utf-8", newline="\n")
print("docs copied")

# Accent colours with the wave + ring burst (design: Accent) as an ES module.
# Only PhoneGyro.accent is taken from bundle.js; it listens for clicks on
# [data-accent-pick] by itself.
js = (DESIGN / "components" / "bundle.js").read_text(encoding="utf-8")
a0 = js.index("  PG.accent = (function () {")
a1 = js.index("  })();", a0) + len("  })();")
acc = js[a0:a1].replace("  PG.accent = (function () {", "export const accent = (function () {", 1).replace("PG.accent.", "accent.")
(OUT / "js" / "vendor").mkdir(exist_ok=True)
(OUT / "js" / "vendor" / "accent.js").write_text(
    "// GENERATED by tools/design-css/build.py from docs/internal/Design/components/bundle.js\n"
    "// (PhoneGyro.accent). Do not edit.\n" + acc + "\n", encoding="utf-8", newline="\n")
print("accent.js", (OUT / "js" / "vendor" / "accent.js").stat().st_size, "bytes")

# GyroScene 3D stage and minimal GLB reader (design: GyroScene) as an ES module.
# Exports { createScene, loadGLB, tintGamepad } and attaches them to window.PhoneGyro.
g0 = js.index("  /* ============ GyroScene: themed Three.js stage")
g1 = js.index("  /* splash: PhoneGyro.playSplash")
scene_code = js[g0:g1].rstrip()
gyro_file = (
    "// GENERATED by tools/design-css/build.py from docs/internal/Design/components/bundle.js\n"
    "// (PhoneGyro: loadGLB, tintGamepad, createScene). Do not edit.\n"
    "const rootScope = typeof window !== 'undefined' ? window : globalThis;\n"
    "const PG = rootScope.PhoneGyro = rootScope.PhoneGyro || {};\n\n"
    + scene_code + "\n\n"
    "export const loadGLB = PG.loadGLB;\n"
    "export const tintGamepad = PG.tintGamepad;\n"
    "export const createScene = PG.createScene;\n"
    "export default PG.createScene;\n"
)
(OUT / "js" / "vendor" / "gyroscene.js").write_text(gyro_file, encoding="utf-8", newline="\n")
print("gyroscene.js", (OUT / "js" / "vendor" / "gyroscene.js").stat().st_size, "bytes")

