"""Builds gui/frontend/src/css/pg.css from the design system (docs/internal/Design).

The design system ships tokens.css and components/bundle.css with the textures
inlined as data URIs (~150 KB). The app keeps them as files instead: they are
cached, decoded once, and the stylesheet stays ~65 KB of rules. Run after the
design system changes:

    python tools/design-css/build.py

Needs Pillow only to (re)write the grain WebP files.
"""
import base64
import io
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from units import px_to_rem  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[2]
DESIGN = ROOT / "docs" / "internal" / "Design"
OUT = ROOT / "gui" / "frontend" / "src"

tokens = (DESIGN / "tokens.css").read_text(encoding="utf-8")
bundle = (DESIGN / "components" / "bundle.css").read_text(encoding="utf-8")

# Fonts live in src/fonts, the stylesheet in src/css.
tokens = tokens.replace('url("fonts/', 'url("../fonts/')

# Texture variables: grain as WebP files, rings from the procedural generator
# (js/rings.js sets --tex-rings-gen-*) with the design tile as the fallback.
grains = re.findall(r'--tex-grain:url\("data:image/png;base64,([^"]+)"\)', bundle)
assert len(grains) == 2, "expected light and dark grain"
try:
    from PIL import Image

    for name, b64 in zip(("light", "dark"), grains):
        img = Image.open(io.BytesIO(base64.b64decode(b64)))
        img.save(OUT / "img" / f"grain-{name}.webp", "WEBP", lossless=True, method=6)
except ImportError:
    print("Pillow missing: grain WebP files not rewritten")

bundle = re.sub(
    r':root,\[data-theme="light"\]\{--tex-rings:url\("data:[^"]+"\);--tex-grain:url\("data:[^"]+"\)\}',
    ':root,[data-theme="light"]{--tex-rings:var(--tex-rings-gen-light,url(../img/rings-light.svg));--tex-grain:url(../img/grain-light.webp)}',
    bundle,
)
bundle = re.sub(
    r'\[data-theme="dark"\]\{--tex-rings:url\("data:[^"]+"\);--tex-grain:url\("data:[^"]+"\)\}',
    '[data-theme="dark"]{--tex-rings:var(--tex-rings-gen-dark,url(../img/rings-dark.svg));--tex-grain:url(../img/grain-dark.webp)}',
    bundle,
)
assert "data:image" not in bundle, "an inlined image is left"

# The design ships px; the app's standard is rem (tools/design-css/units.py).
header = "/* GENERATED by tools/design-css/build.py from docs/internal/Design (px converted to rem). Do not edit: app styles go in app.css. */\n"
(OUT / "css" / "pg.css").write_text(header + px_to_rem(tokens + "\n" + bundle), encoding="utf-8", newline="\n")
print("pg.css", (OUT / "css" / "pg.css").stat().st_size, "bytes")

# The 3D bubble level (design: Level3D) as an ES module. Only createLevel is
# taken: bundle.js also auto-mounts levels through a MutationObserver on the
# whole document and loads Three.js from a CDN, neither of which the app wants
# (the app loads its local three.min.js itself, see js/ui/level.js).
js = (DESIGN / "components" / "bundle.js").read_text(encoding="utf-8")
start = js.index("  PG.createLevel = function (el, opts) {")
end = js.index("  /* declarative mount")
body = js[start:end].rstrip().replace("  PG.createLevel = function (el, opts) {", "export function createLevel(el, opts) {", 1)
assert body.endswith("};"), "createLevel's end moved"
body = body[:-2] + "}"
(OUT / "js" / "vendor").mkdir(exist_ok=True)
HEAD = ("// GENERATED by tools/design-css/build.py from docs/internal/Design/components/bundle.js\n"
        "// (PhoneGyro.createLevel). Do not edit. Needs window.THREE (r128).\n")
(OUT / "js" / "vendor" / "level3d.js").write_text(HEAD + body + "\n", encoding="utf-8", newline="\n")
print("level3d.js", (OUT / "js" / "vendor" / "level3d.js").stat().st_size, "bytes")
