// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdateNow() {
  return window['go']['app']['App']['CheckUpdateNow']();
}

export function ClearPreview() {
  return window['go']['app']['App']['ClearPreview']();
}

export function CloseCemuNotice(arg1) {
  return window['go']['app']['App']['CloseCemuNotice'](arg1);
}

export function CloseFirewallAlert() {
  return window['go']['app']['App']['CloseFirewallAlert']();
}

export function CloseUpdateNotice(arg1) {
  return window['go']['app']['App']['CloseUpdateNotice'](arg1);
}

export function CloseWindow() {
  return window['go']['app']['App']['CloseWindow']();
}

export function ConfirmCloseChoice(arg1, arg2) {
  return window['go']['app']['App']['ConfirmCloseChoice'](arg1, arg2);
}

export function CopyCalibrationReport() {
  return window['go']['app']['App']['CopyCalibrationReport']();
}

export function CopyLast20Frames() {
  return window['go']['app']['App']['CopyLast20Frames']();
}

export function DeleteProfile(arg1) {
  return window['go']['app']['App']['DeleteProfile'](arg1);
}

export function DisableDebug() {
  return window['go']['app']['App']['DisableDebug']();
}

export function DisconnectDSUClient(arg1) {
  return window['go']['app']['App']['DisconnectDSUClient'](arg1);
}

export function FocusDSUClient(arg1) {
  return window['go']['app']['App']['FocusDSUClient'](arg1);
}

export function GetAppSettings() {
  return window['go']['app']['App']['GetAppSettings']();
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function GetAxisAlignStatus() {
  return window['go']['app']['App']['GetAxisAlignStatus']();
}

export function GetCloseAction() {
  return window['go']['app']['App']['GetCloseAction']();
}

export function GetDSUStatus() {
  return window['go']['app']['App']['GetDSUStatus']();
}

export function GetDataDir() {
  return window['go']['app']['App']['GetDataDir']();
}

export function GetDebugStats() {
  return window['go']['app']['App']['GetDebugStats']();
}

export function GetDefaultAppSettings() {
  return window['go']['app']['App']['GetDefaultAppSettings']();
}

export function GetFirewallStatus() {
  return window['go']['app']['App']['GetFirewallStatus']();
}

export function GetFontScale() {
  return window['go']['app']['App']['GetFontScale']();
}

export function GetHideAuthor() {
  return window['go']['app']['App']['GetHideAuthor']();
}

export function GetInputMode() {
  return window['go']['app']['App']['GetInputMode']();
}

export function GetLang() {
  return window['go']['app']['App']['GetLang']();
}

export function GetLanguages() {
  return window['go']['app']['App']['GetLanguages']();
}

export function GetProfiles() {
  return window['go']['app']['App']['GetProfiles']();
}

export function GetResourceStats() {
  return window['go']['app']['App']['GetResourceStats']();
}

export function GetSplash() {
  return window['go']['app']['App']['GetSplash']();
}

export function GetState() {
  return window['go']['app']['App']['GetState']();
}

export function GetTheme() {
  return window['go']['app']['App']['GetTheme']();
}

export function GetUpdateStatus() {
  return window['go']['app']['App']['GetUpdateStatus']();
}

export function GetTranslations(arg1) {
  return window['go']['app']['App']['GetTranslations'](arg1);
}

export function GetWizardMount() {
  return window['go']['app']['App']['GetWizardMount']();
}

export function IsDebugActive() {
  return window['go']['app']['App']['IsDebugActive']();
}

export function IsFirstLaunch() {
  return window['go']['app']['App']['IsFirstLaunch']();
}

export function MarkFirstLaunchDone() {
  return window['go']['app']['App']['MarkFirstLaunchDone']();
}

export function OpenDataDir() {
  return window['go']['app']['App']['OpenDataDir']();
}

export function OpenLiveDebugWindow() {
  return window['go']['app']['App']['OpenLiveDebugWindow']();
}

export function PendingCemuNotice() {
  return window['go']['app']['App']['PendingCemuNotice']();
}

export function PendingFirewallAlert() {
  return window['go']['app']['App']['PendingFirewallAlert']();
}

export function PendingUpdate() {
  return window['go']['app']['App']['PendingUpdate']();
}

export function PlaySystemSound(arg1) {
  return window['go']['app']['App']['PlaySystemSound'](arg1);
}

export function PreviewMatrix(arg1) {
  return window['go']['app']['App']['PreviewMatrix'](arg1);
}

export function PushDebug(arg1, arg2) {
  return window['go']['app']['App']['PushDebug'](arg1, arg2);
}

export function QuitApp() {
  return window['go']['app']['App']['QuitApp']();
}

export function ReconnectDSUClient(arg1) {
  return window['go']['app']['App']['ReconnectDSUClient'](arg1);
}

export function RegenerateDSUMAC() {
  return window['go']['app']['App']['RegenerateDSUMAC']();
}

export function ResetAHRS() {
  return window['go']['app']['App']['ResetAHRS']();
}

export function SaveAppSettings(arg1) {
  return window['go']['app']['App']['SaveAppSettings'](arg1);
}

export function SaveCSVFile(arg1, arg2) {
  return window['go']['app']['App']['SaveCSVFile'](arg1, arg2);
}

export function SaveProfile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SaveProfile'](arg1, arg2, arg3, arg4, arg5);
}

export function SetActiveProfile(arg1) {
  return window['go']['app']['App']['SetActiveProfile'](arg1);
}

export function SetCloseAction(arg1) {
  return window['go']['app']['App']['SetCloseAction'](arg1);
}

export function SetFontScale(arg1) {
  return window['go']['app']['App']['SetFontScale'](arg1);
}

export function SetHideAuthor(arg1) {
  return window['go']['app']['App']['SetHideAuthor'](arg1);
}

export function SetInputMode(arg1) {
  return window['go']['app']['App']['SetInputMode'](arg1);
}

export function SetLang(arg1) {
  return window['go']['app']['App']['SetLang'](arg1);
}

export function SetProfileMountEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetProfileMountEnabled'](arg1, arg2);
}

export function SetSplash(arg1) {
  return window['go']['app']['App']['SetSplash'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['app']['App']['SetTheme'](arg1);
}

export function SetTuningActive(arg1) {
  return window['go']['app']['App']['SetTuningActive'](arg1);
}

export function SetTuningFilterParams(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetTuningFilterParams'](arg1, arg2, arg3);
}

export function SetWindowTheme(arg1) {
  return window['go']['app']['App']['SetWindowTheme'](arg1);
}

export function SetWizardMountEnabled(arg1) {
  return window['go']['app']['App']['SetWizardMountEnabled'](arg1);
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function StartAxisAlign(arg1) {
  return window['go']['app']['App']['StartAxisAlign'](arg1);
}

export function StartCapture() {
  return window['go']['app']['App']['StartCapture']();
}

export function StopCapture(arg1) {
  return window['go']['app']['App']['StopCapture'](arg1);
}

export function ToggleDebugWindow() {
  return window['go']['app']['App']['ToggleDebugWindow']();
}

export function TogglePause() {
  return window['go']['app']['App']['TogglePause']();
}

export function UIReady() {
  return window['go']['app']['App']['UIReady']();
}

export function ValidateCalibration(arg1, arg2) {
  return window['go']['app']['App']['ValidateCalibration'](arg1, arg2);
}

export function ValidateSync() {
  return window['go']['app']['App']['ValidateSync']();
}

export function WriteDebugLog(arg1) {
  return window['go']['app']['App']['WriteDebugLog'](arg1);
}
