// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {settings} from '../models';
import {version} from '../models';
import {app} from '../models';
import {firewall} from '../models';
import {profiles} from '../models';
import {motion} from '../models';

export function CheckUpdateNow():Promise<void>;

export function ClearPreview():Promise<void>;

export function CloseCemuNotice(arg1:boolean):Promise<void>;

export function CloseFirewallAlert():Promise<void>;

export function CloseUpdateNotice(arg1:boolean):Promise<void>;

export function CloseWindow():Promise<void>;

export function ConfirmCloseChoice(arg1:string,arg2:boolean):Promise<void>;

export function CopyCalibrationReport():Promise<string>;

export function CopyLast20Frames():Promise<string>;

export function DeleteProfile(arg1:number):Promise<string>;

export function DisableDebug():Promise<void>;

export function DisconnectDSUClient(arg1:string):Promise<string>;

export function FocusDSUClient(arg1:string):Promise<string>;

export function GetAppSettings():Promise<settings.Settings>;

export function GetAppVersion():Promise<version.Info>;

export function GetAxisAlignStatus():Promise<app.AxisAlignStatus>;

export function GetCloseAction():Promise<string>;

export function GetDSUStatus():Promise<Record<string, any>>;

export function GetDataDir():Promise<string>;

export function GetDebugStats():Promise<app.DebugStats>;

export function GetDefaultAppSettings():Promise<settings.Settings>;

export function GetFirewallStatus():Promise<firewall.Status>;

export function GetFontScale():Promise<number>;

export function GetHideAuthor():Promise<boolean>;

export function GetInputMode():Promise<string>;

export function GetLang():Promise<string>;

export function GetLanguages():Promise<Array<string>>;

export function GetProfiles():Promise<Array<profiles.View>>;

export function GetResourceStats():Promise<Record<string, any>>;

export function GetSplash():Promise<boolean>;

export function GetState():Promise<app.AppState>;

export function GetTheme():Promise<string>;

export function GetUpdateStatus():Promise<app.UpdateStatus>;

export function GetTranslations(arg1:string):Promise<string>;

export function GetWizardMount():Promise<motion.MountCorrection>;

export function IsDebugActive():Promise<boolean>;

export function IsFirstLaunch():Promise<boolean>;

export function MarkFirstLaunchDone():Promise<void>;

export function OpenDataDir():Promise<string>;

export function OpenLiveDebugWindow():Promise<void>;

export function PendingCemuNotice():Promise<app.CemuNotice>;

export function PendingFirewallAlert():Promise<firewall.Status>;

export function PendingUpdate():Promise<app.UpdateInfo>;

export function PlaySystemSound(arg1:string):Promise<void>;

export function PreviewMatrix(arg1:any):Promise<void>;

export function PushDebug(arg1:string,arg2:Record<string, any>):Promise<void>;

export function QuitApp():Promise<void>;

export function ReconnectDSUClient(arg1:string):Promise<string>;

export function RegenerateDSUMAC():Promise<string>;

export function ResetAHRS():Promise<void>;

export function SaveAppSettings(arg1:settings.Settings):Promise<Record<string, any>>;

export function SaveCSVFile(arg1:string,arg2:string):Promise<string>;

export function SaveProfile(arg1:number,arg2:string,arg3:string,arg4:string,arg5:any):Promise<string>;

export function SetActiveProfile(arg1:number):Promise<string>;

export function SetCloseAction(arg1:string):Promise<void>;

export function SetFontScale(arg1:number):Promise<void>;

export function SetHideAuthor(arg1:boolean):Promise<void>;

export function SetInputMode(arg1:string):Promise<string>;

export function SetLang(arg1:string):Promise<void>;

export function SetProfileMountEnabled(arg1:number,arg2:boolean):Promise<string>;

export function SetSplash(arg1:boolean):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetTuningActive(arg1:boolean):Promise<void>;

export function SetTuningFilterParams(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SetWindowTheme(arg1:string):Promise<void>;

export function SetWizardMountEnabled(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function StartAxisAlign(arg1:boolean):Promise<void>;

export function StartCapture():Promise<void>;

export function StopCapture(arg1:number):Promise<app.CaptureResult>;

export function ToggleDebugWindow():Promise<void>;

export function TogglePause():Promise<app.AppState>;

export function UIReady():Promise<void>;

export function ValidateCalibration(arg1:any,arg2:any):Promise<app.ValidationResult>;

export function ValidateSync():Promise<Array<string>>;

export function WriteDebugLog(arg1:Array<string>):Promise<void>;
