// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDeviceStatus() {
  return window['go']['app']['LiveDebugApp']['GetDeviceStatus']();
}

export function GetFullStatus() {
  return window['go']['app']['LiveDebugApp']['GetFullStatus']();
}

export function OpenInFolder(arg1) {
  return window['go']['app']['LiveDebugApp']['OpenInFolder'](arg1);
}

export function ResetAHRS() {
  return window['go']['app']['LiveDebugApp']['ResetAHRS']();
}

export function SaveCSVFile(arg1, arg2) {
  return window['go']['app']['LiveDebugApp']['SaveCSVFile'](arg1, arg2);
}

export function SetWindowTheme(arg1) {
  return window['go']['app']['LiveDebugApp']['SetWindowTheme'](arg1);
}
